import "template_model.dart";

const List<JournalTemplate> kTemplates = [
  // ─────────────────────────────────────────────────────────────────────────
  // T01 — Daily Session Log  (all phases, all practices)
  // ─────────────────────────────────────────────────────────────────────────
  JournalTemplate(
    id: "T01",
    name: "Daily Session Log",
    practiceId: "ALL",
    fields: [
      TemplateField(
        id: "f1",
        label: "Phase",
        inputType: "text",
        placeholder: "Current phase number",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f2",
        label: "Week",
        inputType: "text",
        placeholder: "Week number within phase",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f3",
        label: "Morning Practice",
        inputType: "text",
        placeholder: "Practice name and duration (min)",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f4",
        label: "Morning Observations",
        inputType: "text",
        placeholder: "Notable observations from morning block",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f5",
        label: "Midday/Afternoon Practice",
        inputType: "text",
        placeholder: "Practice name and duration (min)",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f6",
        label: "Midday/Afternoon Observations",
        inputType: "text",
        placeholder: "Notable observations from midday block",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f7",
        label: "Evening Practice",
        inputType: "text",
        placeholder: "Practice name and duration (min)",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f8",
        label: "Evening Observations",
        inputType: "text",
        placeholder: "Notable observations from evening block",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f9",
        label: "Overall Internal Weather",
        inputType: "text",
        placeholder: "One sentence describing today's internal state",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f10",
        label: "Surprises or Confusions",
        inputType: "text",
        placeholder: "Anything that surprised or confused you today",
        voiceEnabled: true,
      ),
    ],
  ),

  // ─────────────────────────────────────────────────────────────────────────
  // T02 — Emotion Check-In Log  (Practice 1D)
  // ─────────────────────────────────────────────────────────────────────────
  JournalTemplate(
    id: "T02",
    name: "Emotion Check-In Log",
    practiceId: "1D",
    fields: [
      TemplateField(
        id: "f1",
        label: "Check-In Time",
        inputType: "timestamp",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f2",
        label: "Emotion Name",
        inputType: "text",
        placeholder: "Name the emotion as precisely as possible",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f3",
        label: "Intensity (0–10)",
        inputType: "scale",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f4",
        label: "Body Location",
        inputType: "text",
        placeholder: "Where in the body is this emotion felt?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f5",
        label: "Notes",
        inputType: "text",
        placeholder: "Context or anything worth noting",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f6",
        label: "Pattern Across Today",
        inputType: "text",
        placeholder: "One sentence describing the pattern across all check-ins",
        voiceEnabled: true,
      ),
    ],
  ),

  // ─────────────────────────────────────────────────────────────────────────
  // T03 — Physiological Journal  (Practice 2A)
  // ─────────────────────────────────────────────────────────────────────────
  JournalTemplate(
    id: "T03",
    name: "Physiological Journal",
    practiceId: "2A",
    fields: [
      TemplateField(
        id: "f1",
        label: "Time on Waking",
        inputType: "timestamp",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f2",
        label: "Heart Rate Estimate (bpm)",
        inputType: "text",
        placeholder: "Estimated heart rate on waking",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f3",
        label: "Heart Quality",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f4",
        label: "Breath Depth",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f5",
        label: "Breath Rate",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f6",
        label: "Breath Restriction",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f7",
        label: "Breath Restriction Location",
        inputType: "text",
        placeholder: "Where is the restriction felt?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f8",
        label: "Gut State",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f9",
        label: "Gut Notes",
        inputType: "text",
        placeholder: "Any additional gut sensation details",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f10",
        label: "Muscle Tension Areas",
        inputType: "text",
        placeholder: "Any obvious tension areas noticed on waking",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f11",
        label: "Overall Arousal (0–10)",
        inputType: "scale",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f12",
        label: "Deviation from Personal Neutral",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f13",
        label: "Deviation Description",
        inputType: "text",
        placeholder: "Describe how today differs from your personal neutral",
        voiceEnabled: true,
      ),
    ],
  ),

  // ─────────────────────────────────────────────────────────────────────────
  // T04 — Gradient Log  (Practice 2D)
  // ─────────────────────────────────────────────────────────────────────────
  JournalTemplate(
    id: "T04",
    name: "Gradient Log",
    practiceId: "2D",
    fields: [
      TemplateField(
        id: "f1",
        label: "Time",
        inputType: "timestamp",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f2",
        label: "Emotion",
        inputType: "text",
        placeholder: "Name the emotion detected",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f3",
        label: "Intensity (0–10)",
        inputType: "scale",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f4",
        label: "What Preceded This?",
        inputType: "text",
        placeholder: "Context, thought, or event that preceded the shift",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f5",
        label: "Source Attribution",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f6",
        label: "Body Location / Physical Signature",
        inputType: "text",
        placeholder: "Where is this felt and what does it feel like physically?",
        voiceEnabled: true,
      ),
    ],
  ),

  // ─────────────────────────────────────────────────────────────────────────
  // T05 — Emotion-Body Map Entry  (Practice 2B)
  // ─────────────────────────────────────────────────────────────────────────
  JournalTemplate(
    id: "T05",
    name: "Emotion-Body Map Entry",
    practiceId: "2B",
    fields: [
      TemplateField(
        id: "f1",
        label: "Emotion Being Mapped",
        inputType: "text",
        placeholder: "Name of the emotion being documented",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f2",
        label: "Induction Method",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f3",
        label: "Body Region 1",
        inputType: "text",
        placeholder: "First body region where this emotion is present",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f4",
        label: "Physical Quality 1",
        inputType: "text",
        placeholder: "Physical quality at region 1 (e.g. pressure, heat, tightness)",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f5",
        label: "Body Region 2",
        inputType: "text",
        placeholder: "Second body region where this emotion is present",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f6",
        label: "Physical Quality 2",
        inputType: "text",
        placeholder: "Physical quality at region 2",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f7",
        label: "Body Region 3",
        inputType: "text",
        placeholder: "Third body region where this emotion is present",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f8",
        label: "Physical Quality 3",
        inputType: "text",
        placeholder: "Physical quality at region 3",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f9",
        label: "Peak Intensity (0–10)",
        inputType: "scale",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f10",
        label: "Onset Speed",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f11",
        label: "Fade Speed",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f12",
        label: "Identifiable from Somatic Cues Alone",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f13",
        label: "Difference from Similar Emotion",
        inputType: "text",
        placeholder: "How does this differ from a similar emotion?",
        voiceEnabled: true,
      ),
    ],
  ),

  // ─────────────────────────────────────────────────────────────────────────
  // T06 — Thought Observation Session Log  (Practice 3B)
  // ─────────────────────────────────────────────────────────────────────────
  JournalTemplate(
    id: "T06",
    name: "Thought Observation Session Log",
    practiceId: "3B",
    fields: [
      TemplateField(
        id: "f1",
        label: "Duration (min)",
        inputType: "text",
        placeholder: "Session duration in minutes",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f2",
        label: "% Spent Observing",
        inputType: "scale",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f3",
        label: "% Spent Merged",
        inputType: "scale",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f4",
        label: "Thought Types Hardest to Observe",
        inputType: "text",
        placeholder: "Which thought types were hardest to observe without merging?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f5",
        label: "Real-Time Catches This Session",
        inputType: "text",
        placeholder: "Number of real-time catches this session",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f6",
        label: "Example Catch",
        inputType: "text",
        placeholder: "An example: I notice I am having the thought...",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f7",
        label: "Moments of Clear Sustained Observation",
        inputType: "text",
        placeholder: "Describe any moments of clear, sustained observation",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f8",
        label: "SMS-Mind Note",
        inputType: "text",
        placeholder: "SMS-Mind score if administered this session",
        voiceEnabled: true,
      ),
    ],
  ),

  // ─────────────────────────────────────────────────────────────────────────
  // T07 — Cognitive Mode Journal  (Practice 3C)
  // ─────────────────────────────────────────────────────────────────────────
  JournalTemplate(
    id: "T07",
    name: "Cognitive Mode Journal",
    practiceId: "3C",
    fields: [
      TemplateField(
        id: "f1",
        label: "Entry Time",
        inputType: "timestamp",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f2",
        label: "Mode",
        inputType: "text",
        placeholder: "e.g. Analyzing, Ruminating, Daydreaming, Narratizing",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f3",
        label: "Confidence",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f4",
        label: "Duration Estimate",
        inputType: "text",
        placeholder: "How long were you in this mode?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f5",
        label: "Trigger if Known",
        inputType: "text",
        placeholder: "What triggered or entered you into this mode?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f6",
        label: "Dominant Mode Today",
        inputType: "text",
        placeholder: "Which mode dominated today?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f7",
        label: "New Modes Noticed",
        inputType: "text",
        placeholder: "Any modes noticed for the first time today?",
        voiceEnabled: true,
      ),
    ],
  ),

  // ─────────────────────────────────────────────────────────────────────────
  // T08 — Process Awareness Journal  (Practice 4A)
  // ─────────────────────────────────────────────────────────────────────────
  JournalTemplate(
    id: "T08",
    name: "Process Awareness Journal",
    practiceId: "4A",
    fields: [
      TemplateField(
        id: "f1",
        label: "Cognitive Activity Reviewed",
        inputType: "text",
        placeholder: "Which task or period are you reviewing?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f2",
        label: "How Was I Thinking?",
        inputType: "text",
        placeholder: "Mode, quality, and shortcuts used",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f3",
        label: "Shortcut or Collapsed Reasoning 1",
        inputType: "text",
        placeholder: "First shortcut or collapsed reasoning you can identify",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f4",
        label: "Shortcut or Collapsed Reasoning 2",
        inputType: "text",
        placeholder: "Second shortcut or collapsed reasoning (if any)",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f5",
        label: "Reasoning Direction",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f6",
        label: "Reasoning Direction Example",
        inputType: "text",
        placeholder: "Give a concrete example of forward or backward reasoning",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f7",
        label: "Would Better Reasoning Have Changed Output?",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f8",
        label: "What Would Have Been Different?",
        inputType: "text",
        placeholder: "If yes, what would higher-quality reasoning have produced?",
        voiceEnabled: true,
      ),
    ],
  ),

  // ─────────────────────────────────────────────────────────────────────────
  // T09 — Assumption Log  (Practice 4C)
  // ─────────────────────────────────────────────────────────────────────────
  JournalTemplate(
    id: "T09",
    name: "Assumption Log",
    practiceId: "4C",
    fields: [
      TemplateField(
        id: "f1",
        label: "Assumption 1 — Statement Treated as Observation",
        inputType: "text",
        placeholder: "What did you treat as a fact without evidence?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f2",
        label: "Assumption 1 — Actual Evidence",
        inputType: "text",
        placeholder: "What did you actually have evidence for?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f3",
        label: "Assumption 1 — What Would Confirm It?",
        inputType: "text",
        placeholder: "What would you need to genuinely know this vs. infer it?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f4",
        label: "Assumption 1 — Timing of Catch",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f5",
        label: "Assumption 2 — Statement Treated as Observation",
        inputType: "text",
        placeholder: "Second assumption treated as fact (if any)",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f6",
        label: "Assumption 2 — Actual Evidence",
        inputType: "text",
        placeholder: "What evidence did you actually have?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f7",
        label: "Assumption 2 — Timing of Catch",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f8",
        label: "Real-Time Catches This Week (Running Count)",
        inputType: "text",
        placeholder: "Running total of real-time assumption catches this week",
        voiceEnabled: true,
      ),
    ],
  ),

  // ─────────────────────────────────────────────────────────────────────────
  // T10 — Narrative Catch Log  (Practice 4D)
  // ─────────────────────────────────────────────────────────────────────────
  JournalTemplate(
    id: "T10",
    name: "Narrative Catch Log",
    practiceId: "4D",
    fields: [
      TemplateField(
        id: "f1",
        label: "Time",
        inputType: "timestamp",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f2",
        label: "Story Content",
        inputType: "text",
        placeholder: "I am telling myself a story about...",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f3",
        label: "Theme (1–3 words)",
        inputType: "text",
        placeholder: "Short label for this narrative theme",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f4",
        label: "Context When It Appeared",
        inputType: "text",
        placeholder: "What was happening when this narrative started?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f5",
        label: "Timing of Catch",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f6",
        label: "Familiar Narrative?",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f7",
        label: "Familiar Narrative Name",
        inputType: "text",
        placeholder: "Name of this narrative if it has appeared before",
        voiceEnabled: true,
      ),
    ],
  ),

  // ─────────────────────────────────────────────────────────────────────────
  // T11 — Emotion Source Log  (Practice 4E)
  // ─────────────────────────────────────────────────────────────────────────
  JournalTemplate(
    id: "T11",
    name: "Emotion Source Log",
    practiceId: "4E",
    fields: [
      TemplateField(
        id: "f1",
        label: "Time",
        inputType: "timestamp",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f2",
        label: "Emotion",
        inputType: "text",
        placeholder: "Name the emotion",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f3",
        label: "Intensity (0–10)",
        inputType: "scale",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f4",
        label: "Source Attribution",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f5",
        label: "Internal Source Specification",
        inputType: "text",
        placeholder: "Memory, belief, anticipation, or ongoing thought pattern?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f6",
        label: "External Source Specification",
        inputType: "text",
        placeholder: "Person, environment, media, or event?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f7",
        label: "Reasoning for Attribution",
        inputType: "text",
        placeholder: "What is your evidence for this attribution?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f8",
        label: "Affect-Cognition Coupling?",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f9",
        label: "Conclusion Being Shaped",
        inputType: "text",
        placeholder: "If coupling present, what conclusion was this emotion shaping?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f10",
        label: "Coupling Pattern",
        inputType: "text",
        placeholder: "Describe the affect-cognition coupling pattern",
        voiceEnabled: true,
      ),
    ],
  ),

  // ─────────────────────────────────────────────────────────────────────────
  // T12 — Contagion Audit  (Practice 4F)
  // ─────────────────────────────────────────────────────────────────────────
  JournalTemplate(
    id: "T12",
    name: "Contagion Audit",
    practiceId: "4F",
    fields: [
      TemplateField(
        id: "f1",
        label: "Week Ending",
        inputType: "timestamp",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f2",
        label: "Instance 1 — Source",
        inputType: "text",
        placeholder: "Source of the emotional contagion instance",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f3",
        label: "Instance 1 — Emotion Transferred",
        inputType: "text",
        placeholder: "Which emotion was transferred?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f4",
        label: "Instance 1 — Intensity (0–10)",
        inputType: "scale",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f5",
        label: "Instance 1 — Aware During Transfer?",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f6",
        label: "Instance 1 — How Could I Have Noticed Earlier?",
        inputType: "text",
        placeholder: "What earlier signal could have alerted you to the contagion?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f7",
        label: "Instance 2 — Source",
        inputType: "text",
        placeholder: "Source of the second contagion instance (if any)",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f8",
        label: "Instance 2 — Emotion Transferred",
        inputType: "text",
        placeholder: "Which emotion was transferred in instance 2?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f9",
        label: "Instance 2 — Intensity (0–10)",
        inputType: "scale",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f10",
        label: "Instance 2 — Aware During Transfer?",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f11",
        label: "High-Contagion Contexts Mapped So Far",
        inputType: "text",
        placeholder: "Contexts where you are most susceptible to emotional contagion",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f12",
        label: "Predictive Accuracy This Week",
        inputType: "text",
        placeholder: "Predicted ___ instances, detected ___ total",
        voiceEnabled: true,
      ),
    ],
  ),

  // ─────────────────────────────────────────────────────────────────────────
  // T13 — Weekly Baseline Review  (Practice 5B)
  // ─────────────────────────────────────────────────────────────────────────
  JournalTemplate(
    id: "T13",
    name: "Weekly Baseline Review",
    practiceId: "5B",
    fields: [
      TemplateField(
        id: "f1",
        label: "Week Number Since Baseline",
        inputType: "text",
        placeholder: "Number of weeks since baseline document was created",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f2",
        label: "Am I Still the Person in My Baseline?",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f3",
        label: "Noticeable Shifts",
        inputType: "text",
        placeholder: "Describe any noticeable shifts from baseline",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f4",
        label: "Significant Drift",
        inputType: "text",
        placeholder: "Describe any significant drift from baseline",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f5",
        label: "Was Drift Deliberate?",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f6",
        label: "Possible Cause of Undeliberate Drift",
        inputType: "text",
        placeholder: "What might have caused this drift if it was not chosen?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f7",
        label: "Values Alignment This Week",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f8",
        label: "Notable Values Departures",
        inputType: "text",
        placeholder: "Describe any notable departures from your Values Document",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f9",
        label: "Overall Note on Current Self",
        inputType: "text",
        placeholder: "One sentence on who you are right now",
        voiceEnabled: true,
      ),
    ],
  ),

  // ─────────────────────────────────────────────────────────────────────────
  // T14 — Pattern Library Entry  (Practice 8A)
  // ─────────────────────────────────────────────────────────────────────────
  JournalTemplate(
    id: "T14",
    name: "Pattern Library Entry",
    practiceId: "8A",
    fields: [
      TemplateField(
        id: "f1",
        label: "Pattern Name",
        inputType: "text",
        placeholder: "Short name for this pattern",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f2",
        label: "Date First Documented",
        inputType: "timestamp",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f3",
        label: "Trigger",
        inputType: "text",
        placeholder: "What reliably precedes this pattern?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f4",
        label: "Sequence Step 1",
        inputType: "text",
        placeholder: "First step in the pattern sequence",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f5",
        label: "Sequence Step 2",
        inputType: "text",
        placeholder: "Second step in the pattern sequence",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f6",
        label: "Sequence Step 3",
        inputType: "text",
        placeholder: "Third step in the pattern sequence",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f7",
        label: "Behavioral Tendency",
        inputType: "text",
        placeholder: "What behavioral outcome does this pattern produce?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f8",
        label: "Somatic Signature",
        inputType: "text",
        placeholder: "What does this pattern feel like in the body at the start?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f9",
        label: "Context",
        inputType: "text",
        placeholder: "Where and when does this pattern appear most?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f10",
        label: "Earliest Detectable Point",
        inputType: "text",
        placeholder: "What is the first signal that this pattern is starting?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f11",
        label: "Interruption Action",
        inputType: "text",
        placeholder: "Pre-decided action to interrupt this pattern",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f12",
        label: "Update History",
        inputType: "text",
        placeholder: "Notes on how understanding of this pattern has evolved",
        voiceEnabled: true,
      ),
    ],
  ),

  // ─────────────────────────────────────────────────────────────────────────
  // T15 — Pattern Interruption Log  (Practice 8B)
  // ─────────────────────────────────────────────────────────────────────────
  JournalTemplate(
    id: "T15",
    name: "Pattern Interruption Log",
    practiceId: "8B",
    fields: [
      TemplateField(
        id: "f1",
        label: "Time",
        inputType: "timestamp",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f2",
        label: "Pattern Name",
        inputType: "text",
        placeholder: "Which pattern was triggered?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f3",
        label: "Trigger Context",
        inputType: "text",
        placeholder: "Describe the situation that triggered the pattern",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f4",
        label: "Interruption Attempted?",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f5",
        label: "Why No Attempt?",
        inputType: "text",
        placeholder: "If no attempt was made, why not?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f6",
        label: "Did the Pattern Complete Despite Interruption?",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f7",
        label: "Earliest Detection Point This Instance",
        inputType: "text",
        placeholder: "At what point did you detect the pattern this time?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f8",
        label: "Interruption Action Used",
        inputType: "text",
        placeholder: "Which action did you use to interrupt the pattern?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f9",
        label: "Notes on What Worked or Didn't",
        inputType: "text",
        placeholder: "What helped or hindered the interruption?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f10",
        label: "Running Success Rate for This Pattern",
        inputType: "text",
        placeholder: "Total successes / total attempts = %",
        voiceEnabled: true,
      ),
    ],
  ),

  // ─────────────────────────────────────────────────────────────────────────
  // T16 — Reframing Exercise Log  (Practice 8C)
  // ─────────────────────────────────────────────────────────────────────────
  JournalTemplate(
    id: "T16",
    name: "Reframing Exercise Log",
    practiceId: "8C",
    fields: [
      TemplateField(
        id: "f1",
        label: "Original Framing",
        inputType: "text",
        placeholder: "I believe / I tell myself / The story I hold is...",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f2",
        label: "Alternative Framing 1",
        inputType: "text",
        placeholder: "If this framing were accurate instead...",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f3",
        label: "Implications of Framing 1",
        inputType: "text",
        placeholder: "What would the implications be for your situation?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f4",
        label: "Alternative Framing 2",
        inputType: "text",
        placeholder: "If this framing were accurate instead...",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f5",
        label: "Implications of Framing 2",
        inputType: "text",
        placeholder: "What would the implications be for your situation?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f6",
        label: "Alternative Framing 3",
        inputType: "text",
        placeholder: "If this framing were accurate instead...",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f7",
        label: "Implications of Framing 3",
        inputType: "text",
        placeholder: "What would the implications be for your situation?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f8",
        label: "Self-Check — Genuine or Motivated Reframing?",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f9",
        label: "Change in Relationship to Original Framing",
        inputType: "text",
        placeholder: "How has your relationship to the original framing changed?",
        voiceEnabled: true,
      ),
    ],
  ),

  // ─────────────────────────────────────────────────────────────────────────
  // T17 — Practice Quality Assessment  (Practice 7E)
  // ─────────────────────────────────────────────────────────────────────────
  JournalTemplate(
    id: "T17",
    name: "Practice Quality Assessment",
    practiceId: "7E",
    fields: [
      TemplateField(
        id: "f1",
        label: "Practice Name",
        inputType: "text",
        placeholder: "Name of the Layer 3 practice just completed",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f2",
        label: "Duration (min)",
        inputType: "text",
        placeholder: "Session duration in minutes",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f3",
        label: "Behavioral Relevance (1–5)",
        inputType: "scale",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f4",
        label: "Behavioral Relevance Notes",
        inputType: "text",
        placeholder: "Was this practice genuinely meaningful to you?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f5",
        label: "Appropriate Challenge (1–5)",
        inputType: "scale",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f6",
        label: "Appropriate Challenge Notes",
        inputType: "text",
        placeholder: "Were you engaged without being overwhelmed?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f7",
        label: "Contextual Variety (1–5)",
        inputType: "scale",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f8",
        label: "Contextual Variety Notes",
        inputType: "text",
        placeholder: "Was today's context varied from recent sessions?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f9",
        label: "Intentional Engagement (1–5)",
        inputType: "scale",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f10",
        label: "Intentional Engagement Notes",
        inputType: "text",
        placeholder: "Were you actively present or running on autopilot?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f11",
        label: "Total Score (out of 20)",
        inputType: "text",
        placeholder: "Sum of all four criteria scores",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f12",
        label: "Criteria Dragging Score Down",
        inputType: "text",
        placeholder: "If total < 12, which criteria are lowest?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f13",
        label: "Adjustment for Next Session",
        inputType: "text",
        placeholder: "What will you change to improve quality next session?",
        voiceEnabled: true,
      ),
    ],
  ),

  // ─────────────────────────────────────────────────────────────────────────
  // T18 — Recovery Time Log  (Practice 5F)
  // ─────────────────────────────────────────────────────────────────────────
  JournalTemplate(
    id: "T18",
    name: "Recovery Time Log",
    practiceId: "5F",
    fields: [
      TemplateField(
        id: "f1",
        label: "Time of Disruption",
        inputType: "timestamp",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f2",
        label: "Disruption Type",
        inputType: "text",
        placeholder: "Brief description of the disruption",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f3",
        label: "Pre-Disruption Monitoring Quality (1–5)",
        inputType: "scale",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f4",
        label: "Monitoring Quality at +5 min (1–5)",
        inputType: "scale",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f5",
        label: "Monitoring Quality at +10 min (1–5)",
        inputType: "scale",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f6",
        label: "Monitoring Quality at +15 min (1–5)",
        inputType: "scale",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f7",
        label: "Monitoring Quality at +30 min (1–5)",
        inputType: "scale",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f8",
        label: "Monitoring Quality at +60 min (1–5)",
        inputType: "scale",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f9",
        label: "Recovery Time (minutes)",
        inputType: "text",
        placeholder: "Minutes until monitoring quality returned to pre-disruption level",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f10",
        label: "Notes on What Helped or Hindered",
        inputType: "text",
        placeholder: "What helped or slowed recovery?",
        voiceEnabled: true,
      ),
    ],
  ),

  // ─────────────────────────────────────────────────────────────────────────
  // T19 — Directed Practice Cycle Document  (Practice 8E)
  // ─────────────────────────────────────────────────────────────────────────
  JournalTemplate(
    id: "T19",
    name: "Directed Practice Cycle Document",
    practiceId: "8E",
    fields: [
      TemplateField(
        id: "f1",
        label: "Cycle Start Date",
        inputType: "timestamp",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f2",
        label: "Target Completion Date",
        inputType: "timestamp",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f3",
        label: "Target Pattern Name",
        inputType: "text",
        placeholder: "Pattern name from your topology map",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f4",
        label: "Current Manifestation",
        inputType: "text",
        placeholder: "How does this pattern present currently?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f5",
        label: "Why This Pattern Is a Priority",
        inputType: "text",
        placeholder: "What makes this pattern worth working on now?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f6",
        label: "Desired Outcome",
        inputType: "text",
        placeholder: "What concrete behavior would replace the current pattern?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f7",
        label: "Practice Design — Specific Repetition",
        inputType: "text",
        placeholder: "What specific repetition will build the replacement pattern?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f8",
        label: "Behavioral Relevance Check",
        inputType: "text",
        placeholder: "Why is this practice meaningful to you?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f9",
        label: "Challenge Level (1–5)",
        inputType: "scale",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f10",
        label: "Challenge Level Adjustment",
        inputType: "text",
        placeholder: "If > 4 or < 2, how will you adjust difficulty?",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f11",
        label: "Context Variety Plan",
        inputType: "text",
        placeholder: "List at least 3 different contexts for this practice",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f12",
        label: "Pre-Measure 1 Label",
        inputType: "text",
        placeholder: "Name of first baseline measure",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f13",
        label: "Pre-Measure 1 Baseline Value",
        inputType: "text",
        placeholder: "Baseline value before cycle starts",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f14",
        label: "Pre-Measure 2 Label",
        inputType: "text",
        placeholder: "Name of second baseline measure",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f15",
        label: "Pre-Measure 2 Baseline Value",
        inputType: "text",
        placeholder: "Baseline value before cycle starts",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f16",
        label: "Weekly Notes",
        inputType: "text",
        placeholder: "Quality score, notable changes, and adjustments for each week",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f17",
        label: "Post-Measure 1 End Value",
        inputType: "text",
        placeholder: "Value of first measure at cycle end",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f18",
        label: "Post-Measure 2 End Value",
        inputType: "text",
        placeholder: "Value of second measure at cycle end",
        voiceEnabled: true,
      ),
      TemplateField(
        id: "f19",
        label: "Did the Pattern Change as Intended?",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f20",
        label: "Continue Cycle?",
        inputType: "checklist",
        placeholder: null,
        voiceEnabled: false,
      ),
      TemplateField(
        id: "f21",
        label: "Key Learning from This Cycle",
        inputType: "text",
        placeholder: "What did you learn from this directed practice cycle?",
        voiceEnabled: true,
      ),
    ],
  ),
];
